### ISSUE TITLE
New CSS @apply rule causes crash

### ISSUE THREAD

**Issue by Nektro** [mariocasciaro/gulp-concat-css#37]
The new CSS @apply rule decribed [here](https://tabatkins.github.io/specs/css-apply-rule/) causes a crash.
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: C:\GitHubWeb\CssMaterial\src\components\button.css:17:5: missing '}'
    at error (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:62:15)
    at declarations (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:259:26)
    at rule (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:560:21)
    at rules (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:117:70)
    at stylesheet (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:81:21)
    at module.exports (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\node_modules\css\lib\parse\index.js:564:20)
    at rework (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\rework\index.js:27:21)
    at DestroyableTransform._transform (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\index.js:82:22)
    at DestroyableTransform.Transform._read (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\GitHubWeb\CssMaterial\node_modules\gulp-concat-css\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
```
The referenced file can be found [here](https://github.com/Nektro/CssMaterial/blob/master/src/components/button.css).

Although not technically standard CSS, it has [already shipped](https://www.chromestatus.com/feature/5753701012602880) in Chrome and Opera.

**Comment by arbaev** [comment]
The same problem with **@media** and so on.

**Comment by edthedev** [comment]
Also crashes on `@starting-style`, as well.

(Reference: https://github.com/app-illinois/Design-Resources/actions/runs/15425927428/job/43412692337 )
